image: openjdk:8-alpine

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_VERSION: "4.10.2"
  GRADLE_HOME: "/opt/gradle"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - wget -qO - "https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip" | unzip -d /tmp -
  - mkdir "${GRADLE_HOME%/*}" && mv "/tmp/gradle-${GRADLE_VERSION}" "${GRADLE_HOME}/" && chmod 755 "${GRADLE_HOME}/bin/gradle" && ln -vs "${GRADLE_HOME}/bin/gradle" /usr/bin/gradle
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - apk add --no-cache git

build:
  stage: build
  script:
    - gradle --build-cache assemble javadoc publish generateGitVersionName
    - java -jar build/libs/*-all.jar --help > build/help.txt
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

test:
  stage: test
  script: gradle check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

pages:
  stage: deploy
  dependencies:
    - test
  script:
    - mkdir -p public
    - mv LICENSE build/distributions build/docs/javadoc build/mvn-repo build/help.txt public/
    - mv build/libs/*.jar public/distributions/
    - ./generate-webpage.sh public > public/index.html
  artifacts:
    paths:
      - public
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
